services:
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true
    simonetti.bundle.ping.lock_store:
        class: Simonetti\PingBundle\Lock\PersistingFileStorage
    simonetti.bundle.ping.lock_factory:
        class: Symfony\Component\Lock\LockFactory
        arguments: ['@simonetti.bundle.ping.lock_store']
    simonetti.bundle.ping.lock:
        class: Symfony\Component\Lock\Lock
        factory: ['@simonetti.bundle.ping.lock_factory', createLock]
        arguments: ['', null, false]
    simonetti.bundle.ping.controller.ping_action:
        class: Simonetti\PingBundle\Controller\PingAction
        arguments: ['@simonetti.bundle.ping.lock']
        public: true
    pimonetti.pingbundle.command.lock_command:
        class: Simonetti\PingBundle\Command\LockCommand
        arguments: ['@simonetti.bundle.ping.lock']
        tags: ['console.command']
    pimonetti.pingbundle.command.ping_command:
        class: Simonetti\PingBundle\Command\PingCommand
        arguments: ['@simonetti.bundle.ping.lock']
        tags: ['console.command']
