name: CI

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        symfony-version: ['^4', '^5', '^6']
        php-versions: ['7.4', '8.0', '8.1']
        prefer: [lowest, stable]
        exclude:
          - symfony-version: '^6'
            php-version: '7.4'

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Install dependencies
        run: |
          sed -i  "s/\(symfony\/[^\"]*\)\": \"\([^\*]*\)\"/\1\": \"${{ matrix.symfony-version }}\"/" composer.json
          composer install --prefer-${{ matrix.prefer }}

      - name: Run commands
        run: |
          php Tests/console ping:lock
          php Tests/console ping:lock -r
          php Tests/console ping
