name: CI

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        symfony-version: ["^6", "^7"]
        php-version: ["8.1", "8.2"]
        prefer: [lowest, stable]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sed -i  "s/\(symfony\/[^\"]*\)\": \"\([^\*]*\)\"/\1\": \"${{ matrix.symfony-version }}\"/" composer.json
          composer update --prefer-${{ matrix.prefer }} --prefer-dist

      - name: Run commands
        run: |
          php Tests/console ping:lock
          php Tests/console ping:lock -r
          php Tests/console ping
